const discs: any = {
  buttercup: "https://www.youtube.com/watch?v=eYDI8b5Nn5s",
  canttell: "https://www.youtube.com/watch?v=Mvw05bimpvk",
  caramelldansen: "https://www.youtube.com/watch?v=A67ZkAd1wmI",
  caramelldansen_original: "https://www.youtube.com/watch?v=zvq9r6R6QAY",
  corpse_agoraphobic: "https://www.youtube.com/watch?v=ra-XCs6LHAM",
  corpse_cabinfever: "https://www.youtube.com/watch?v=imHLUbO6hPQ",
  corpse_catgirls: "https://www.youtube.com/watch?v=Yl6t_8pldzU",
  corpse_egirls: "https://www.youtube.com/watch?v=W5d4SJv2d6M",
  corpse_missyou: "https://www.youtube.com/watch?v=clnIeauiVDM",
  corpse_neversatisfied: "https://www.youtube.com/watch?v=cCc7yTpRGcI",
  corpse_whitetee: "https://www.youtube.com/watch?v=yS6aXxdL6M8",
  lofi: "https://www.youtube.com/watch?v=5qap5aO4i9A",
  morshu: "https://www.youtube.com/watch?v=cJs7r0TLfx0",
  pigstep: "https://www.youtube.com/watch?v=8aZ7oB2chEU",
  pigstep_remix: "https://www.youtube.com/watch?v=r_a4Zg3PyA0",
  pissbaby: "https://www.youtube.com/watch?v=0avFvn3Chyg",
  tetris: "https://www.youtube.com/watch?v=h-lkp-JcL-A",
};
export default discs;
